export const API=
{
    getCoacheesByCoach: "/api/getCoacheesByCoach",
    getMeetingTypes: "/api/getMeetingTypes",
    createTouchpoint: "/api/createTouchpoint",
    getABSModules:"/api/getABSModules",
    getModuleDetails:"/api/getModuleDetails",
    updateABSModule:"/api/updateABSModule",
    getAllABSModules:"/api/getAllABSModules",
    createModule:"/api/createModule",
    getSelectedABSModule:"/api/getSelectedABSModule",
    updateSelectedModule:"/api/updateSelectedModule",
    deleteModule:"/api/deleteModule",
    getCapByID:"/api/getCapByCoachee",
    getTriadNotes:"/api/getTriadNotes",
    getAllCaps:"/api/getAllCaps",
    postTriad:"/api/postTriad",
    //Coachee Selector & Coachee Profile     
    coacheeList: "/api/getCoacheeList",
    coacheeInfo: "/api/getCoacheeInfo",
    //Survey Stuff
    getSurveysByCoachee: "/api/getSurveysByCoachee",
    getAllSurveyTypes: "/api/getAllSurveyTypes",
    createSurveyRecord: "/api/createSurveyRecord",
    postGradCap:'/api/postGradCap',
    companyList:'/api/getCompany',
    departmentList:'/api/getDepartment',
    managerList:'/api/getManager',
    supervisorList:'/api/getSupervior',
    vpList:'/api/getVP',
}